# Commented sections below can be used to run tests on the CI server
# https://simulatedgreg.gitbooks.io/electron-vue/content/en/testing.html#on-the-subject-of-ci-testing
osx_image: xcode9.2
sudo: required
dist: trusty

language: node_js
node_js:
  - 8

matrix:
  include:
  - os: osx
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang

cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
    #- xvfb

before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  #    wget -qO - https://dl.winehq.org/wine-builds/Release.key | sudo apt-key add -;
  #    sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/;
  #  fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --install-recommends winehq-stable ; fi

  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi

install:
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=':99.0' ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & ; fi
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - npm install -g xvfb-maybe

  - $CC --version
  - $CXX --version
  - npm --version
  - yarn --version

  - yarn

script:
  #- xvfb-maybe node_modules/.bin/karma start test/unit/karma.conf.js
  #- yarn run pack && xvfb-maybe node_modules/.bin/mocha test/e2e
  - yarn run lint
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run release:linux ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn run release ; fi

branches:
  only:
  - master
